return {
	Accent = Color3.fromRGB(0, 200, 100), 

	AcrylicMain = Color3.fromRGB(12, 24, 12),      
	AcrylicBorder = Color3.fromRGB(50, 100, 50),   
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(0, 80, 40), Color3.fromRGB(0, 40, 20)),
	AcrylicNoise = 0.92,

	TitleBarLine = Color3.fromRGB(50, 100, 50),
	Tab = Color3.fromRGB(100, 200, 100),

	Element = Color3.fromRGB(30, 70, 30),
	ElementBorder = Color3.fromRGB(20, 50, 20),
	InElementBorder = Color3.fromRGB(255, 215, 0), 
	ElementTransparency = 0.84,

	ToggleSlider = Color3.fromRGB(100, 200, 100),
	ToggleToggled = Color3.fromRGB(0, 0, 0),

	SliderRail = Color3.fromRGB(100, 200, 100),

	DropdownFrame = Color3.fromRGB(150, 220, 150),
	DropdownHolder = Color3.fromRGB(30, 80, 30),
	DropdownBorder = Color3.fromRGB(20, 60, 20),
	DropdownOption = Color3.fromRGB(100, 200, 100),

	Keybind = Color3.fromRGB(100, 200, 100),

	Input = Color3.fromRGB(100, 200, 100),
	InputFocused = Color3.fromRGB(20, 10, 30),
	InputIndicator = Color3.fromRGB(150, 255, 150),

	Dialog = Color3.fromRGB(30, 80, 30),
	DialogHolder = Color3.fromRGB(20, 60, 20),
	DialogHolderLine = Color3.fromRGB(15, 45, 15),
	DialogButton = Color3.fromRGB(30, 80, 30),
	DialogButtonBorder = Color3.fromRGB(80, 150, 80),
	DialogBorder = Color3.fromRGB(50, 120, 50),
	DialogInput = Color3.fromRGB(35, 90, 35),
	DialogInputLine = Color3.fromRGB(150, 255, 150),

	Text = Color3.fromRGB(240, 240, 240),
	SubText = Color3.fromRGB(180, 180, 180),

	Hover = Color3.fromRGB(100, 200, 100),
	HoverChange = 0.04
}
