return {
	Accent = Color3.fromRGB(180, 180, 200),      -- Soft Silver

	AcrylicMain = Color3.fromRGB(5, 5, 8),
	AcrylicBorder = Color3.fromRGB(60, 60, 70),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(30, 30, 35), Color3.fromRGB(10, 10, 15)),
	AcrylicNoise = 0.92,

	TitleBarLine = Color3.fromRGB(60, 60, 70),
	Tab = Color3.fromRGB(140, 140, 150),

	Element = Color3.fromRGB(40, 40, 45),
	ElementBorder = Color3.fromRGB(20, 20, 25),
	InElementBorder = Color3.fromRGB(100, 100, 110),
	ElementTransparency = 0.85,

	ToggleSlider = Color3.fromRGB(130, 130, 140),
	ToggleToggled = Color3.fromRGB(0, 0, 0),

	SliderRail = Color3.fromRGB(130, 130, 140),

	DropdownFrame = Color3.fromRGB(70, 70, 80),
	DropdownHolder = Color3.fromRGB(30, 30, 35),
	DropdownBorder = Color3.fromRGB(20, 20, 25),
	DropdownOption = Color3.fromRGB(130, 130, 140),

	Keybind = Color3.fromRGB(130, 130, 140),

	Input = Color3.fromRGB(130, 130, 140),
	InputFocused = Color3.fromRGB(10, 10, 12),
	InputIndicator = Color3.fromRGB(170, 170, 180),

	Dialog = Color3.fromRGB(30, 30, 35),
	DialogHolder = Color3.fromRGB(20, 20, 25),
	DialogHolderLine = Color3.fromRGB(15, 15, 18),
	DialogButton = Color3.fromRGB(30, 30, 35),
	DialogButtonBorder = Color3.fromRGB(70, 70, 80),
	DialogBorder = Color3.fromRGB(50, 50, 60),
	DialogInput = Color3.fromRGB(35, 35, 40),
	DialogInputLine = Color3.fromRGB(170, 170, 180),

	Text = Color3.fromRGB(230, 230, 240),
	SubText = Color3.fromRGB(160, 160, 170),
	Hover = Color3.fromRGB(130, 130, 140),
	HoverChange = 0.04
}
