return {
	Accent = Color3.fromRGB(255, 184, 77),       -- Goldenish Orange

	AcrylicMain = Color3.fromRGB(40, 25, 15),
	AcrylicBorder = Color3.fromRGB(180, 130, 70),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(200, 140, 60), Color3.fromRGB(120, 80, 30)),
	AcrylicNoise = 0.92,

	TitleBarLine = Color3.fromRGB(180, 130, 70),
	Tab = Color3.fromRGB(240, 180, 100),

	Element = Color3.fromRGB(190, 130, 70),
	ElementBorder = Color3.fromRGB(80, 50, 20),
	InElementBorder = Color3.fromRGB(220, 160, 90),
	ElementTransparency = 0.87,

	ToggleSlider = Color3.fromRGB(240, 170, 80),
	ToggleToggled = Color3.fromRGB(0, 0, 0),

	SliderRail = Color3.fromRGB(240, 170, 80),

	DropdownFrame = Color3.fromRGB(250, 200, 130),
	DropdownHolder = Color3.fromRGB(100, 60, 30),
	DropdownBorder = Color3.fromRGB(70, 40, 15),
	DropdownOption = Color3.fromRGB(240, 170, 80),

	Keybind = Color3.fromRGB(240, 170, 80),

	Input = Color3.fromRGB(240, 170, 80),
	InputFocused = Color3.fromRGB(40, 25, 15),
	InputIndicator = Color3.fromRGB(255, 210, 140),

	Dialog = Color3.fromRGB(100, 60, 30),
	DialogHolder = Color3.fromRGB(70, 40, 15),
	DialogHolderLine = Color3.fromRGB(50, 30, 10),
	DialogButton = Color3.fromRGB(100, 60, 30),
	DialogButtonBorder = Color3.fromRGB(150, 100, 50),
	DialogBorder = Color3.fromRGB(130, 80, 40),
	DialogInput = Color3.fromRGB(110, 70, 35),
	DialogInputLine = Color3.fromRGB(255, 210, 140),

	Text = Color3.fromRGB(255, 240, 220),
	SubText = Color3.fromRGB(200, 170, 140),
	Hover = Color3.fromRGB(240, 170, 80),
	HoverChange = 0.04
}
